## Setup java: download, unarchive

- name: Check if java folder exists.
  stat: path={{java_home}}
  register: java_home_check

- name: Log if java folder exists.
  debug: msg="JAVA_HOME = {{java_home}} exist, skipping java tasks"
  when: java_home_check.stat.exists

- name: Log if java folder does not exist.
  debug: msg="JAVA_HOME = {{java_home}} does not exist, downloading from {{java_url}}"
  when: not java_home_check.stat.exists

- name: Download java.
  get_url: url={{java_url}} dest={{tmp_folder}}/
  register: downloaded_java_archive
  when: not java_home_check.stat.exists

- name: Make java tmp folder
  file: path={{java_tmp_folder}} state=directory
  when: not java_home_check.stat.exists

- name: Unarchive java archive.
  unarchive: src={{downloaded_java_archive.dest}} dest={{java_tmp_folder}}/ copy=no
  register: unarhive_java
  when: not java_home_check.stat.exists

- name: Create java folder.
  file: path={{java_home}} state=directory
  when: not java_home_check.stat.exists

- name: Move unpacked archive to java folder.
  shell: mv {{java_tmp_folder}}/* {{java_home}}/
  when: not java_home_check.stat.exists

- name: Remove empty folder.
  file: path={{java_tmp_folder}} state=absent
  when: not java_home_check.stat.exists

- name: Remove archive.
  file: path={{downloaded_java_archive.dest}} state=absent
  when: not java_home_check.stat.exists

